### ISSUE TITLE
send-keys not working for C-l

### ISSUE THREAD

**Issue by jondkinney** [tmux-plugins/tmux-sensible#16]
Hi again,

I have this setting:

```
# allow clearing of screen in a shell
bind C-l send-keys 'C-l'
```

Which allows me to hit `C-a-l` which is prefix, then hold down control and press lower case L. It's supposed to do the default thing that ctrl-l does and clear the screen. I'm not sure exactly what in tmux-sensible is blocking that, but I get navigated to the right pane instead of it doing the intended thing. 

Before I had tmux-sensible installed I did have the same settings it has to navigate splits by prefix h,j,k,l so I know there is a way to have the two co-exist.

If you have any ideas that'd be much appreciated. Thanks!

**Comment by bruno-** [comment]
Hey, are you sure you also don't have [tmux-pain-control](https://github.com/tmux-plugins/tmux-pain-control) plugin installed? Because the behavior you describe is exactly what that plugin gives you.

To clarify, `pain-control` remaps `prefix + hjkl` to move around the panes, but it also adds the `control` version of `hjkl`.

In each case, I'm fairly sure `tmux-sensible` is innocent here :smile: .
If you want to make sure what's causing the trouble, type `tmux list-keys` in the terminal (within tmux). You'll get a list of all the key mappings and you can find what `C-l` is mapped to.

I think some of this should help you, so because there are a ton of open issues on `tmux-plugins` I'm going to close this one. If things are still unclear or you have questions, please feel free to reopen.

**Comment by jondkinney** [comment]
Hey @bruno- 

I think you're right, that this isn't an issue with tmux-sensible but rather with tmux-pain-control. When I was configuring everything manually I was able to have ctrl-hjkl move me between panes (like pain-control does) and also still have the ability to clear the screen with `ctrl-a, ctrl-l`. Would you like me to file an issue over there?

**Comment by bruno-** [comment]
Hey, sure, open an issue there.
