### ISSUE TITLE
set base-index and pane-base-index to 1

### ISSUE THREAD

**Issue by aleprovencio** [tmux-plugins/tmux-sensible#22]
Hello @bruno- !
why did you leave them off tmux-sensible?

**Comment by bruno-** [comment]
Well, I prefer to have base index 0.

**Comment by aleprovencio** [comment]
Fair enough! And sorry about being so vague.

But as you said on another issue (https://github.com/tmux-plugins/tmux-pain-control/issues/6) you use the tmux book (i guess the one from pragmatic bookshelf) as a reference and they also seem to use these defaults.

I myself find this more aligned with other tools I use such as firefox and i3wm.

**Comment by bruno-** [comment]
Hey @aleprovencio,
yes, I often use pragmatic bookshelf tmux book as a reference for standard tmux configuration. However, this repo has more strict requirements than that: we strive for no one having objections to installing it.

If we add base-index and pane-base-index 1, then I'd have an objection and there's the requirement broken.

I do encourage you to try to make a more opinionated plugin.

**Comment by aleprovencio** [comment]
I agree about this but don't you think that it would bring the "almost sensible options" thing back?
I'm also very curious on why you find the indexes better starting from 0. You've already made my workflow improve on many ways and there's always more room for that :)

**Comment by bruno-** [comment]
Thank you for the positive remark there, I'm glad I improved things in some way.

About the indices starting from 0 preference: for me this is the ease of pressing number keys on the keyboard.

Number keys 4, 5, 6 and 7 have to be pressed with the index finger and this subjectively feels like moving away from the home row (also maybe my index fingers are short). 6 is especially hard and the right hand has to move a lot. I find hitting keys with middle, ring or pinky fingers easier. When index fingers don't move, returning the hand fully to the home row feels easier. From this perspective, I prefer having 0 as one extra easy number to type before hitting window numbers 4 and above.

All this is subtle and might be completely different for other people.

> don't you think that it would bring the "almost sensible options" thing back?

Yea, this is almost sensible since I guess a lot of people have this option set. Well, you can't please everyone. Sometimes you gotta take a stand and be useful for part of the people.

**Comment by aleprovencio** [comment]
Ah, that's a good story and a good reason for you to keep'em 0-indexed. Thanks again for your time, and keep the great work. You can close the issue if you want.
