### ISSUE TITLE
Plugin returns 127 

### ISSUE THREAD

**Issue by wikimatze** [tmux-plugins/tmux-sensible#30]
Hi Bruno,

I have tmux 2.1 running and started using your plugin to get rid of standard settings everybody should use in tmux. When starting tmux, I get the following message:

``` sh
tmux source-file .tmux.conf 
'/home/wm/clone/path/sensible.tmux' returned 127
```

You can find my `tmux.conf` here https://github.com/wikimatze/dotfiles/blob/master/tmux.conf.

Maybe the issue lies in my settings or in the latest tmux version.

**Comment by bruno-** [comment]
Hey,
your `tmux.conf` looks all good, just remove the `run-shell ~/clone/path/sensible.tmux` line from the bottom and everything should work.

The error happens because you're trying to run a script (with `run-shell`) that does not exist (in this path: `~/clone/path/sensible.tmux`) and that's why you get error 127.

The error line was most likely copy-pasted from the readme by accident. It's not needed because you're using tmux plugin manager to run plugins.

Hope this helps.

**Comment by wikimatze** [comment]
Yeah, that was the solution, thanks for having a look into it.

**Comment by bruno-** [comment]
Great.
