### ISSUE TITLE
Setting your prefix key to C-\ breaks key_binding_not_set

### ISSUE THREAD

**Issue by futuro** [tmux-plugins/tmux-sensible#36]
If your prefix is `C-\` then key_binding_not_set inserts a single escape character into the grep regex, which causes it to fail. The following line tests for and fixes this special case.

`if [[ ${key} == '\' ]]; then key='\\'; fi`

PR incoming.

**Comment by josephjang** [comment]
The PR to fix the grep pattern seems to be already filed.

As you know, tmux-sensible uses `tmux list-keys | grep PATTERN` to recognize the status of the key bindings. When the `grep PATTERN` is failed due to a wrong pattern, `tmux list-keys` does not terminate as expected. As the result, tmux fails to load the other plugins and it's just stuck. 

I've filed the problem above as well in https://github.com/tmux/tmux/issues/2694.
